fix system.stateVersion
Addresses this error when switching to the flake:

```
error: Build user group has mismatching GID, aborting activation
The default Nix build user group ID was changed from 30000 to 350.
You are currently managing Nix build users with nix-darwin, but your
nixbld group has GID 350, whereas we expected 30000.

Possible causes include setting up a new Nix installation with an
existing nix-darwin configuration, setting up a new nix-darwin
installation with an existing Nix installation, or manually increasing
your `system.stateVersion` setting.

You can set the configured group ID to match the actual value:

    ids.gids.nixbld = 350;

We do not recommend trying to change the group ID with macOS user
management tools without a complete uninstallation and reinstallation
of Nix.
```